server {
    listen 8000;
    server_name belling.jootang.cn 0.0.0.0; # 客户1的域名


    # 静态资源配置
    location / {
        root /var/www/bellingeel.com;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

#     # 反向代理 Node.js 服务
#     location /api/ {
#         proxy_pass http://localhost:3001; # 客户1的 Node.js 服务端口
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#     }
}

# server {
#     listen 80;
#     server_name customer2.example.com; # 客户2的域名
#
#     # 静态资源配置
#     location / {
#         root /var/www/customer2/static;
#         index index.html;
#         try_files $uri $uri/ /index.html;
#     }
#
#     # 反向代理 Node.js 服务
#     location /api/ {
#         proxy_pass http://localhost:3002; # 客户2的 Node.js 服务端口
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#     }
# }
